CC= g++
CFLAGS= -std=c++98 -g -D_GLIBCXX_DEBUG `~/ClanLib/flags.sh` 
OUTPUT= mario
FILES= mario.cc menu.cc game.cc player.cc koopa.cc goomba.cc shroom.cc coin.cc tile.cc

all:
	$(CC) $(CFLAGS) -o $(OUTPUT) $(FILES)

